name: marl-ppo-suite
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch>=2.0.0
  - torchvision
  - moviepy # for logger
  - imageio
  - imageio-ffmpeg
  - numpy>=1.20.0
  - matplotlib
  - pandas
  - cloudpickle>=2.2.0
  - tqdm
  - pip
  # --- Pip Dependencies ---
  - pip:
      - tensorboard
      - pysc2>=3.0.0 # If specific version/build needed via pip
      - git+https://github.com/oxwhirl/smac.git
      - git+https://github.com/oxwhirl/smacv2.git
      - gymnasium
      - wandb # Optional: Weights & Biases often installed via pip
      - python-dotenv
