name: marl-ppo-suite
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch>=2.0.0
  - torchvision
  - pip
  - pip:
      # Core dependencies
      - numpy>=1.20.0
      - matplotlib
      - pandas
      - tensorboard
      - cloudpickle>=2.2.0

      # RL environments
      - pysc2>=3.0.0
      - git+https://github.com/oxwhirl/smac.git
      - git+https://github.com/oxwhirl/smacv2.git
      - gymnasium

      # Utilities
      - tqdm # Progress bars
      - wandb # Optional: Weights & Biases for experiment tracking
